services:
  - type: web
    name: ai-growify
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: bash startup.sh
    envVars:
      - key: DISPLAY
        value: ":99"
      - key: CHROME_BIN
        value: "/usr/bin/chromium-browser"
      - key: CHROMEDRIVER_PATH
        value: "/usr/bin/chromedriver"
      - key: RENDER
        value: "true"
    headers:
      - source: /.*
        headers:
          - key: Cache-Control
            value: no-store
