services:
  - type: web
    name: growify-ai
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: >
      Xvfb :99 -screen 0 1024x768x24 &
      export DISPLAY=:99 &&
      streamlit run main_dashboard.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.13
