services:
  - type: web
    name: seo-auditor
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run main1.py
    runtime: python
    envVars:
      - key: GEMINI_API_KEY
        value: your_actual_api_key_here
    build:
      aptPackages:
        - xvfb
        - chromium-browser
        - chromium-chromedriver
        - libglib2.0-0
        - libsm6
        - libxrender1
        - libxext6
        - libgl1-mesa-glx
